---
- name: Cockpit setup
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure packages required for playbook exist
      ansible.builtin.package:
        name:
          - cockpit
          - cockpit-packagekit
          - cockpit-pcp
          - cockpit-storaged

    - name: Enable and start cockpit.socket
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: cockpit.socket

    - name: Enable and start pmlogger.service (for metrics)
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: pmlogger.service
