---
- name: Docker setup
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure packages required for playbook exist
      ansible.builtin.package:
        name:
          - docker
          - docker-compose

    - name: Enable and start docker.service
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: docker.service
