---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure packages required for playbook exist
      package:
        name:
          - chezmoi
          - git

    - name: Ensure the main user exists # how to set accompanying gid
      user:
        uid: 1000
        name: main

    - name: Allow the main user to run passworded sudo
      blockinfile:
        path: /etc/sudoers.d/u_main
        create: true
        mode: 0644
        validate: "visudo -cf %s"
        block: |
          main ALL=(ALL) ALL

    - name: Git clone srv
      become: true
      become_user: main
      git:
        force: false # this one is default but i wanted it to be verbose
        update: false
        dest: ~/srv
        repo: https://github.com/voltamage/srv

    - name: ALWAYS CHANGED Fix srv origin
      become: true
      become_user: main
      shell:
        chdir: ~/srv
        cmd: git remote remove origin && git remote add origin git@github.com:voltamage/srv.git
    
    - name: Ensure git directory exists
      become: true
      become_user: main
      file:
        path: ~/.config/git
        state: directory
        mode: 0755
    
    - name: Copy git config
      copy:
        owner: main
        group: main
        force: false
        mode: 0644
        src: /home/main/srv/install/config
        dest: /home/main/.config/git/config

    - name: Ensure .ssh directory exists
      become: true
      become_user: main
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Copy server public key
      copy:
        owner: main
        group: main
        force: false
        decrypt: true
        mode: 0644
        src: /home/main/srv/install/id_ed25519.pub
        dest: /home/main/.ssh/id_ed25519.pub

    - name: Copy server private key
      copy:
        owner: main
        group: main
        force: false
        decrypt: true
        mode: 0600
        src: /home/main/srv/install/id_ed25519
        dest: /home/main/.ssh/id_ed25519
