---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure packages required for playbook exist
      package:
        name:
          - atuin
          - chezmoi
          - fish
          - git
          - lazygit
          - neovim
          - ranger
          - tmux
          - zoxide

    - name: Ensure the main user exists # how to set accompanying gid
      user:
        uid: 1000
        name: main

    - name: Allow the main user to run passworded sudo
      blockinfile:
        path: /etc/sudoers.d/u_main
        create: true
        mode: 0644
        validate: "visudo -cf %s"
        block: |
          main ALL=(ALL) ALL

    - name: Git clone srv
      become: true
      become_user: main
      git:
        force: false # this one is default but i wanted it to be verbose
        update: false
        dest: ~/srv
        repo: https://github.com/voltamage/srv

    - name: ALWAYS CHANGED Fix srv origin
      become: true
      become_user: main
      shell:
        chdir: ~/srv
        cmd: git remote remove origin && git remote add origin git@github.com:voltamage/srv.git

    - name: Ensure chezmoi directory exists
      become: true
      become_user: main
      file:
        path: ~/.config/chezmoi
        state: directory
        mode: 0755

    - name: Configure chezmoi
      become: true
      become_user: main
      blockinfile:
        path: ~/.config/chezmoi/chezmoi.yaml
        create: true
        mode: 0644
        block: |
          sourceDir: ~/srv/chezmoi
    
    - name: Allow the main user to run interactive fish
      become: true
      become_user: main
      blockinfile:
        path: ~/.bashrc
        create: true
        mode: 0644
        block: |
          exec fish
